source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'JPImageresizerView_Example' do
  pod 'JPImageresizerView', :path => '../'

  pod 'JPLiquidLayout'
  pod 'Masonry'
  pod 'pop'
  pod 'SVProgressHUD'
  
  pod 'JPBasic/JPConst'
  pod 'JPBasic/JPCategory'
  pod 'JPBasic/JPProgressHUD'
  pod 'JPBasic/JPBrowseImages'
end
