source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '11.0'

target 'JPImageresizerView_Example' do
  pod 'JPImageresizerView', :path => '../'
  pod 'JPLiquidLayout'
  pod 'JPBasic/JPConst'
  pod 'JPBasic/JPCategory'
  pod 'JPBasic/JPProgressHUD'
  pod 'JPBasic/JPBrowseImages'
  pod 'JPCrop'
  pod 'FunnyButton'
  pod 'LookinServer', :configurations => ['Debug']
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
      end
    end
  end
end
