source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '13.0'

target 'JPImageresizerView_Example' do
  pod 'JPImageresizerView', :path => '../'
  pod 'JPLiquidLayout'
  pod 'JPBasic/JPConst'
  pod 'JPBasic/JPCategory'
  pod 'JPBasic/JPProgressHUD'
  pod 'JPBasic/JPBrowseImages'
  pod 'JPCrop'
  pod 'FunnyButton'
  pod 'LookinServer', :configurations => ['Debug']
end
